name: fixed-point-finder
channels:
dependencies:
    - python=2.7
    - numpy=1.14.5
    - scipy=1.1.0
    - scikit-learn=0.20.0
    - matplotlib=2.2.3
    - PyYAML=3.13
    - tensorflow-gpu=1.10.0
    - pip:
        - "--editable=git://github.com/mattgolub/recurrent-whisperer.git@v1.1.1#egg=recurrent-whisperer"
